REM CURRENT COLORS
SET "currentRed=#E00034"
SET "currentOrange=#F2711C"
SET "currentYellow=#FFA100"
SET "currentOlive=#B5CC18"
SET "currentGreen=#3F9C35"
SET "currentTeal=#00B5AD"
SET "currentBlue=#00549F"
SET "currentViolet=#6435C9"
SET "currentPurple=#A333C8"
SET "currentPink=#E03997"
SET "currentBrown=#A5673F"

REM NEW COLORS
SET "newRed=#E00034"
SET "newOrange=#F2711C"
SET "newYellow=#FFA100"
SET "newOlive=#B5CC18"
SET "newGreen=#3F9C35"
SET "newTeal=#00B5AD"
SET "newBlue=#0D5186"
SET "newViolet=#6435C9"
SET "newPurple=#A333C8"
SET "newPink=#E03997"
SET "newBrown=#C75B32"

REM CURRENT LIGHT COLORS
SET "currentLightRed=#D6002F"
SET "currentLightOrange=#FF851B"
SET "currentLightYellow=#FFE21F"
SET "currentLightOlive=#D9E778"
SET "currentLightGreen=#75A840"
SET "currentLightTeal=#6DFFFF"
SET "currentLightBlue=#0053A1"
SET "currentLightViolet=#A291FB"
SET "currentLightPurple=#DC73FF"
SET "currentLightPink=#FF8EDF"
SET "currentLightBrown=#D67C1C"

REM NEW LIGHT COLORS
SET "newLightRed=#D6002F"
SET "newLightOrange=#FF851B"
SET "newLightYellow=#FFE21F"
SET "newLightOlive=#D9E778"
SET "newLightGreen=#75A840"
SET "newLightTeal=#6DFFFF"
SET "newLightBlue=#3F83B8"
SET "newLightViolet=#A291FB"
SET "newLightPurple=#DC73FF"
SET "newLightPink=#FF8EDF"
SET "newLightBrown=#EF835A"

REM CURRENT NEUTRALS
SET "currentOffWhite=#D9D7D5"
SET "currentDarkWhite=#D0CFCC"

REM CURRENT GREYSCALE
SET "currentFullBlack=#56565A"
SET "currentBlack=#646569"
SET "currentLightBlack=#777679"
SET "currentGrey=#89898C"
SET "currentLightGrey=#989798"
SET "currentMidWhite=#C8C7C6"
SET "currentWhite=#FFFFFF"

REM NEW NEUTRALS 
SET "newOffWhite=#D9D7D5"
SET "newDarkWhite=#D0CFCC"

REM NEW GREYSCALE
SET "newFullBlack=#56565A"
SET "newBlack=#646569"
SET "newLightBlack=#777679"
SET "newGrey=#89898C"
SET "newLightGrey=#989798"
SET "newMidWhite=#C8C7C6"
SET "newWhite=#FFFFFF"

REM CURRENT GENERALS
SET "currentHeaderFont=Exo"
SET "currentFontName=News Gothic MT"

SET "currentPrimaryColor=@blue"
SET "currentSecondaryColor=@black"
SET "currentLightPrimaryColor=@lightBlue"
SET "currentLightSecondaryColor=@lightBlack"
SET "currentButtonBackgroundColor=#E0E1E2";
SET "currentTextColor=@lightBlack"
SET "currentLinkColor=@green"

REM NEW GENERALS
SET "newHeaderFont=Exo"
SET "newFontName=News Gothic MT"

SET "newPrimaryColor=@brown"
SET "newSecondaryColor=@blue"
SET "newLightPrimaryColor=@lightBrown"
SET "newLightSecondaryColor=@lightBlue"
SET "newButtonBackgroundColor=#E0E1E2"
SET "newTextColor=@lightBlack"
SET "newLinkColor=@blue"

REM CURRENT COMPLEX CONCATS
SET "currentPrimary=@primaryColor        : %currentPrimaryColor%"
SET "currentSecondary=@secondaryColor      : %currentSecondaryColor%"
SET "currentLightPrimary=@lightPrimaryColor   : %currentLightPrimaryColor%"
SET "currentLightSecondary=@lightSecondaryColor : %currentLightSecondaryColor%"
SET "currentButtonColor=@buttonBackgroundColor: %currentButtonBackgroundColor%"
SET "currentText=@textColor           : %currentTextColor%"
SET "currentLink=@linkColor           : %currentLinkColor%"

REM NEW COMPLEX CONCATS
SET "newPrimary=@primaryColor        : %newPrimaryColor%"
SET "newSecondary=@secondaryColor      : %newSecondaryColor%"
SET "newLightPrimary=@lightPrimaryColor   : %newLightPrimaryColor%" 
SET "newLightSecondary=@lightSecondaryColor : %newLightSecondaryColor%"
SET "newButtonColor=@buttonBackgroundColor: %newButtonBackgroundColor%"
SET "newText=@textColor           : %newTextColor%"
SET "newLink=@linkColor           : %newLinkColor%"

REM PATHS
SET "basePath=semantic/src/themes/"
SET "targetThemePath=silvana/"
SET "siteVariablesPath=globals/site.variables"
SET "path=%basePath%%targetThemePath%%siteVariablesPath%"


powershell -Command "(gc %path%) -replace '%currentRed%', '%newRed%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentOrange%', '%newOrange%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentYellow%', '%newYellow%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentOlive%', '%newOlive%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentGreen%', '%newGreen%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentTeal%', '%newTeal%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentBlue%', '%newBlue%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentViolet%', '%newViolet%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentPurple%', '%newPurple%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentPink%', '%newPink%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentBrown%', '%newBrown%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentGrey%', '%newGrey%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentBlack%', '%newBlack%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightRed%', '%newLightRed%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightOrange%', '%newLightOrange%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightYellow%', '%newLightYellow%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightOlive%', '%newLightOlive%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightGreen%', '%newLightGreen%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightTeal%', '%newLightTeal%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightBlue%', '%newLightBlue%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightViolet%', '%newLightViolet%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightPurple%', '%newLightPurple%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightPink%', '%newLightPink%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightBrown%', '%newLightBrown%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightGrey%', '%newLightGrey%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightBlack%', '%newLightBlack%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentFullBlack%', '%newFullBlack%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentOffWhite%', '%newOffWhite%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentDarkWhite%', '%newDarkWhite%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentMidWhite%', '%newMidWhite%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentWhite%', '%newWhite%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentHeaderFont%', '%newHeaderFont%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentFontName%', '%newFontName%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentPrimary%', '%newPrimary%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentSecondary%', '%newSecondary%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightPrimary%', '%newLightPrimary%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLightSecondary%', '%newLightSecondary%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentButtonColor%', '%newButtonColor%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentText%', '%newText%' | Out-File -encoding ASCII %path%"
powershell -Command "(gc %path%) -replace '%currentLink%', '%newLink%' | Out-File -encoding ASCII %path%"
